MaxBlog/accounts/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'accounts'

urlpatterns = [

    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('registration/', views.RegisterCreateView.as_view(), name='registration'),
    path('update/user/<int:pk>/', views.UserUpdateView.as_view(), name='update'),

]

MaxBlog/likes/urls.py
from django.urls import path
from . import views


app_name = 'likes'
urlpatterns = [

    ]

MaxBlog/accounts/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin

from .managers import UserManager

class User(AbstractBaseUser ,PermissionsMixin):
    email = models.EmailField (_('email address'), unique=True)
    first_name = models.CharField (_('first name'), max_length=25)
    last_name = models.CharField (_('last name'), max_length=25)
    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    avatar = models.ImageField(_('avatar'), upload_to='avatars/', null=True, blank=True)
    is_staff = models.BooleanField(_('staff'), default=True)
    is_active = models.BooleanField(_('active'), default=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELD = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    @property
    def get_full_name(self):

        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    @property
    def get_short_name(self):

        return self.first_name

MaxBlog/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from django.contrib.auth.hashers import make_password
from django.utils.translation import gettext_lazy as _


class LoginForm(AuthenticationForm):
    username = UsernameField(
        max_length = 40,
        widget=forms.TextInput(
            attrs={
                'autofocus': True,
                'class': 'input form-control',
                'placeholder':'Your Email'
            }
        ),
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'class': 'input form-control',
                'placeholder':'Password'
            }
        )
    )


class CustomUserCreationForm(UserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        strip = False,
        widget=forms.PasswordInput(
            attrs={
                'class':'form-control input'
            }
        )
    )

    password2 = forms.CharField(
        label=_("Confirm Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        ),
    )

    first_name = forms.CharField(
        label = _("First name"),
        strip=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input'
            }
        )
    )

    last_name = forms.CharField(
        label = _("Last name"),
        strip=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input'
            }
        )
    )

    email = forms.CharField(
        label = _("Email"),
        strip=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input'
            }
        )
    )



    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name')


class CustomUserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        label=_("First name"),
        strip=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input'
            }
        ),
    )

    last_name = forms.CharField(
        label=_("Last name"),
        strip=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input'
            }
        ),
    )

    avatar = forms.ImageField(
        label=_("Image"),
        widget=forms.FileInput(),
        required=False
    )

    class Meta:
        model = get_user_model()
        fields = ("first_name", "last_name", "avatar")

MaxBlog/accounts/views.py
from braces.views import AnonymousRequiredMixin
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView, UpdateView

from accounts.forms import LoginForm , CustomUserCreationForm , CustomUserUpdateForm



class CustomLoginView(SuccessMessageMixin, AnonymousRequiredMixin, LoginView):
    template_name = 'accounts/login.html'
    success_url = '/'
    form_class = LoginForm
    success_message = _('You are successfully logged in')


class CustomLogoutView(LogoutView):
    next_page = '/'

class RegisterCreateView(AnonymousRequiredMixin, CreateView):
    model = get_user_model()
    form_class = CustomUserCreationForm
    template_name = "accounts/registration.html"

    def get_success_url(self):
        return reverse_lazy('accounts:login')


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'accounts/registration.html'
    success_url = '/'
    form_class = CustomUserUpdateForm
    succes_message = _('Updated')

    def get_queryset(self):
        return self.model.objects.filter(id=self.request.user.id)
    def get_context_data(self, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        context.update({'btn_text': _('Update')})
        return context

MaxBlog/templates/accounts/login.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>

    <!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:700%7CNunito:300,600" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="{% static 'js/html5shiv.min.js' %}"></script>
		  <script src="{% static 'js/respond.min.js' %}"></script>
		<![endif]-->
<style>
    .mx-auto{
        margin-left: 30% !important;
        margin-right: 30% !important;
        margin-bottom: auto !important;
        margin-top: 20% !important;
    }
</style>
</head>
<body>
<div class="container">
    <div class="col-md-4 col-md-offset-1 mx-auto">
        <div class="section-row">
            <h3>Log In</h3>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="primary-button" type="submit">{% trans 'Sign In' %}</button>
            </form>
            <br>
            <h4><a href="{% url 'accounts:registration' %}">Don't have an account?</h4>
        </div>
    </div>
</div>
</body>
</html>

MaxBlog/templates/accounts/registration.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>

    <!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:700%7CNunito:300,600" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="{% static 'js/html5shiv.min.js' %}"></script>
		  <script src="{% static 'js/respond.min.js' %}"></script>
		<![endif]-->
<style>
    .mx-auto{
        margin-left: 30% !important;
        margin-right: 30% !important;
        margin-bottom: auto !important;
        margin-top: 10% !important;
    }
</style>


</head>
<body>
<div class="container">
    <div class="col-sm-12 col-md-4 col-md-offset-1 mx-auto">
        <div class="section-row">
            <h3>Registration</h3>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="primary-button" type="submit">
                    {% if btn_text %}
                        {{ btn_text }}
                    {% else %}
                        {% trans "Sign up" %}
                    {% endif %}
                </button>
            </form>
            <br>
        </div>
    </div>
</div>
</body>
</html>