MaxBlog/likes/urls.py
from django.urls import path
from . import views


app_name = 'likes'
urlpatterns = [

    ]

MaxBlog/mainpage/urls.py
from django.urls import path
from . import views


app_name = 'mainpage'
urlpatterns = [
    path('', views.PostListView.as_view(), name="list"),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name="detail"),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('update/post/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    ]

MaxBlog/templates/post/includes/content_post.html
{% load i18n %}

                    <!-- post -->
					<div class="col-md-6">
						<div class="post post">
							<a class="post-img" href="{% url 'mainpage:detail' object.id %}"><img src="{{ object.image.url }}"</a>
							<div class="post-body">
								<div class="post-meta">
									<a class="post-category cat-2" href="{{ object.category }}.html">{{ object.category }}</a>
									<span class="post-date">{{ object.create_datetime}}</span>
								</div>
								<h3 class="post-title"><a href="{% url 'mainpage:detail' object.id %}">{{ object.title }}</a></h3>
							</div>
						</div>
					</div>
					<!-- /post -->

MaxBlog/templates/post/includes/thumb_section.html
{% load i18n %}

					<!-- post -->
					<div class="col-md-6">
						<div class="post post-thumb">
							<a class="post-img" href="{% url 'mainpage:detail' object.id %}"><img src="{{ object.image.url }}" alt=""></a>
							<div class="post-body">
								<div class="post-meta">
									<a class="post-category cat-2" href="{{ object.category }}.html">{{ object.category }}</a>
									<span class="post-date">{{ object.create_datetime }}</span>
								</div>
								<h3 class="post-title"><a href="{% url 'mainpage:detail' object.id %}">{{ object.title }}</a></h3>
							</div>
						</div>
					</div>
					<!-- /post -->