MaxBlog/likes/urls.py
from django.urls import path
from . import views


app_name = 'likes'
urlpatterns = [

    ]

MaxBlog/mainpage/urls.py
from django.urls import path
from . import views


app_name = 'mainpage'
urlpatterns = [
    path('', views.PostListView.as_view(), name="list"),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name="detail"),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('update/post/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    ]

MaxBlog/mainpage/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class PostAbstractModel(models.Model):
    created_datetime = models.DateTimeField(_('Creating time'), auto_now_add=True)
    update_datetime = models.DateTimeField(_('Last changing time'), auto_now_add=True)
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE, verbose_name=_('Author'))

    class Meta:
        abstract = True



class Post(PostAbstractModel):
    title = models.CharField(_("Title"), max_length=50)
    second_title = models.CharField(_("Second Title"), max_length=200)
    text = models.TextField(_("News text"))
    category = models.CharField(_("Category"), max_length=20)
    image = models.ImageField(_("News image"), upload_to='news_images/', null=True, blank=False)

    def __str__(self):
        return " ".join([str(self.created_datetime), self.title])

    class Meta:
        ordering = ('-created_datetime',)
        verbose_name = _("News")
        verbose_name_plural = _("News")

MaxBlog/mainpage/forms.py
from .models import Post
from django import forms
from django.utils.translation import ugettext_lazy as _



class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'second_title', 'text', 'image', 'category']
        widgets = {
            'title': forms.TextInput(),
            'second_title': forms.TextInput(),
            'text': forms.Textarea(),
            'category': forms.TextInput(),
        }
        image = forms.ImageField(
            label=_('Title image'),
            widget=forms.FileInput(
                attrs={
                    'class': 'input'
                },
            ),
            required=False
        )
        #category = forms.ModelChoiceField()


        def __init__(self, *args, **kwargs):
            super(CreatePostFormForm, self).__init__(*args, **kwargs)
            self.fields['title'].widget.attrs.update({'class': 'input', name: 'title'})
            self.fields['second_title'].widget.attrs.update({'class': 'input', name: 'Second title'})
            self.fields['text'].widget.attrs.update({'class': 'input', name: 'Text'})
            self.fields['category'].widget.attrs.update({'class': 'input', name: 'Category'})

MaxBlog/mainpage/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, CreateView, DeleteView, UpdateView, ListView
from django.utils.translation import ugettext_lazy as _
from django_filters.views import FilterView
from .models import Post
from .forms import CreatePostForm





def index(request):
    #context = {"object_list": Post.objects.all()}
    return render(request, 'index.html')

class PostListView(ListView):
    queryset = Post.objects.all()
    template_name = 'post/mainpage.html'
    paginate_by = 14


class PostDetailView(DetailView):
    template_name = 'post/blog-post.html'
    queryset = Post.objects.all()

class PostCreateView(CreateView, LoginRequiredMixin):
    form_class = CreatePostForm
    template_name = 'post/form.html'
    queryset = Post.objects.all()

    def get_context_data(self, **kwargs):
        context = super(PostCreateView, self).get_context_data(**kwargs)
        context.update({'btn_text': _('Create')})
        return context

    def form_valid(self, form):
        new_form = form.save(commit=False)
        new_form.author = self.request.user
        new_form.save()
        return HttpResponseRedirect('/')


class PostUpdateView(UpdateView):
    form_class = CreatePostForm
    template_name = 'post/form.html'
    queryset = Post.objects.all()
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super(PostUpdateView, self).get_context_data(**kwargs)
        context.update({'btn_text': _('Update')})
        return context
    def get_success_url(self):
        return reverse_lazy('mainpage:detail', kwargs={'pk': self.object.pk})


class PostDeleteView(DeleteView):
    template_name = 'post/delete_form.html'
    success_url = '/'
    queryset = Post.objects.all()

MaxBlog/templates/post/blog-post.html
{% extends 'index.html' %}
{% load i18n %}
{% load static %}
		{% block header %}
			<div id="post-header" class="page-header">
				<div class="background-img" style="background-image: url('{% static "img/post-page.jpg" %}')"></div>
				<div class="container">
					<div class="row">
						<div class="col-md-10">
							<div class="post-meta">
								<a class="post-category cat-2" href="{{ object.category }}.html">{{ object.category }}</a>
								<span class="post-date">{{ object.created_datetime }}</span>
							</div>
							<h1>{{ object.title }}</h1>
						</div>
					</div>
				</div>
			</div>
		{% endblock %}
		{% block thumb %}
		{% endblock %}

		{% block content %}
		<div class="col-md-12">
						<!-- ad -->

						<div class="section-row sticky-container m-b-lg ">
							<div class="main-post col-md-10">
								<div class="section-row text-center">

								<img class="img-responsive" src="{{ object.image.url }}" alt="">
						</div>

								<h3>{{ object.second_title }}</h3>
								<p>{{ object.text }}</p>
							</div>
							 <a href="{% url 'mainpage:update' object.id  %}">
										<button class="primary-button" type="button">
												{% trans 'Update' %}
										</button>
                                    </a>
									 <a href="{% url 'mainpage:delete' object.id %}">
										<button class="primary-button btn-danger " type="button">
												{% trans 'Delete' %}
										</button>
                                    </a>
							<div class="post-shares sticky-shares">
								<a href="#" class="share-facebook"><i class="fa fa-facebook"></i></a>
								<a href="#" class="share-twitter"><i class="fa fa-twitter"></i></a>
								<a href="#" class="share-google-plus"><i class="fa fa-google-plus"></i></a>
								<a href="#" class="share-pinterest"><i class="fa fa-pinterest"></i></a>
								<a href="#" class="share-linkedin"><i class="fa fa-linkedin"></i></a>
								<a href="#"><i class="fa fa-envelope"></i></a>
							</div>
						</div>



						<!-- author -->
						<div class="section-row">
							<div class="post-author">
								<div class="media">
									<div class="media-left">
										<img class="media-object" src="author.image" alt="">
									</div>
									<div class="media-body">
										<div class="media-heading">
											<h3>{{ author.first_name }} {{ author.last_name }}</h3>
										</div>
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
										<ul class="author-social">
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
											<li><a href="#"><i class="fa fa-instagram"></i></a></li>
										</ul>
									</div>
								</div>
							</div>
						</div>
						<!-- /author -->
						<div class="section-row">
							<div class="section-title">
								<h2>3 Comments</h2>
							</div>

							<div class="post-comments">
								<!-- comment -->
								<div class="media">
									<div class="media-left">
										<img class="media-object" src="./img/avatar.png" alt="">
									</div>
									<div class="media-body">
										<div class="media-heading">
											<h4>John Doe</h4>
											<span class="time">March 27, 2018 at 8:00 am</span>
											<a href="#" class="reply">Reply</a>
										</div>
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>

										<!-- comment -->
										<div class="media">
											<div class="media-left">
												<img class="media-object" src="./img/avatar.png" alt="">
											</div>
											<div class="media-body">
												<div class="media-heading">
													<h4>John Doe</h4>
													<span class="time">March 27, 2018 at 8:00 am</span>
													<a href="#" class="reply">Reply</a>
												</div>
												<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
											</div>
										</div>
										<!-- /comment -->
									</div>
								</div>
								<!-- /comment -->

								<!-- comment -->
								<div class="media">
									<div class="media-left">
										<img class="media-object" src="./img/avatar.png" alt="">
									</div>
									<div class="media-body">
										<div class="media-heading">
											<h4>John Doe</h4>
											<span class="time">March 27, 2018 at 8:00 am</span>
											<a href="#" class="reply">Reply</a>
										</div>
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
									</div>
								</div>
								<!-- /comment -->
							</div>
						</div>
						<!-- /comments -->

						<!-- reply -->
						<div class="section-row">
							<div class="section-title">
								<h2>Leave a reply</h2>
								<p>your email address will not be published. required fields are marked *</p>
							</div>
							<form class="post-reply">
								<div class="row">
									<div class="col-md-4">
										<div class="form-group">
											<span>Name *</span>
											<input class="input" type="text" name="name">
										</div>
									</div>
									<div class="col-md-4">
										<div class="form-group">
											<span>Email *</span>
											<input class="input" type="email" name="email">
										</div>
									</div>
									<div class="col-md-4">
										<div class="form-group">
											<span>Website</span>
											<input class="input" type="text" name="website">
										</div>
									</div>
									<div class="col-md-12">
										<div class="form-group">
											<textarea class="input" name="message" placeholder="Message"></textarea>
										</div>
										<button class="primary-button">Submit</button>
									</div>
								</div>
							</form>
						</div>
						<!-- /reply -->

					</div>
					<!-- /Post content -->
		{% endblock %}

MaxBlog/templates/post/delete_form.html
{% extends 'index.html' %}
{% load i18n %}
{% block thumb %}
{% endblock %}
{% block content %}
<div class="col-md-6 col-md-offset-1">
						<div class="section-row">
							<h3>{% trans 'Are you shure, that you want to delete a post?' %}</h3>
							<form method = "post" enctype="multipart/form-data">
								{% csrf_token %}
								<div class="row">
									    <button class="primary-button" type="submit">
												{% trans 'Yes' %}
										</button>
                                    <a href="{% url 'mainpage:list' %}">
										<button class="primary-button" type="button">
												{% trans 'Now' %}
										</button>
                                    </a>
                                </div>
							</form>
						</div>
</div>
{% endblock %}

MaxBlog/templates/post/form.html
{% extends 'index.html' %}
{% load i18n %}
{% load static %}
{% block thumb %}
{% endblock %}
{% block content %}
<div class="col-md-5 col-md-offset-1">

						<div class="section-row">
							<h3>{% trans 'Create Post' %}</h3>
							<form method = "post" enctype="multipart/form-data">
                            {% csrf_token %}
								<div class="row">
									<div class="col-md-7">
										<div class="form-group">
									<label id = "{{ from.id_for_label }}"><span>{% trans 'Title' %}</span></label>
											{{ form.title }}
										</div>
									</div>
									<div class="col-md-7">
										<div class="form-group">
											<span>{% trans 'Second title' %}</span>
											{{ form.second_title }}
										</div>
									</div>
									<div class="col-md-7">
										<div class="form-group">
											<span>{% trans 'Category' %}</span>
											{{ form.category }}
										</div>
									</div>
									<div class="col-md-12">
										<div class="form-group">
											<span>{% trans 'Text' %}</span>
											{{ form.text }}
										</div>
										<div class="col-md-7">
										<div class="form-group">
											<span>{% trans 'Title image' %}</span>
											{{ form.image }}
										</div>
									</div>
										<button class="primary-button" type="submit">
											{% if btn_text %}
												{{ btn_text }}
											{% else %}
												{% trans 'Button' %}
											{% endif %}
										</button>
									</div>
								</div>
							</form>
						</div>
					</div>
{% endblock %}

MaxBlog/templates/post/mainpage.html
{% extends "index.html" %}
{% load i18n %}
    {% block thumb %}

    {% for obj in object_list|slice:":2" %}
        {% with obj as object %}
            {% include 'post/includes/thumb_section.html' %}
        {% endwith %}
    {% empty %}
        <h1>{% trans 'Nothing to show' %}</h1>
    {% endfor %}
    {% endblock %}



    {% block content %}
        {% for obj in object_list|slice:"2:20" %}
        {% with obj as object %}
            {% include 'post/includes/content_post.html' %}
        {% endwith %}
    {% empty %}
        <h1>{% trans 'Nothing to show' %}</h1>
    {% endfor %}
    <!-- Pagination -->
    <nav aria-label="...">
      <ul class="pagination">

        {% if page_obj.has_previous %}
        <li >
            <a class="page-link" href="?page=1"> {% trans 'First' %}</a>
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;{% trans 'Previos' %}</a>
        </li>
        {% endif %}
        <li class="page-item active">
            <span class="current">
            Page {{ page_obj.number }} {% trans 'of' %} {{ page_obj.paginator.num_pages }}.
        </span>
        </li>
       {% if page_obj.has_next %}
        <li >
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans 'Next' %}&raquo;</a>
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{% trans 'Last' %}</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    <!-- /Pagination -->
    {% endblock %}